### ISSUE TITLE
Is this available on Windows?

### ISSUE THREAD

**Issue by Mustardsauce** [damiles/OpenCVGUI#1]
I'm gonna use this on Windows... but there isn't a installation manual for Windows on your site.

**Comment by damiles** [comment]
You can download and compile it in windows but it's not tested at all and will have some bugs to solve, I will try to compile and finish a first release for windows in few weeks and you will download a precompiled dll

**Comment by Mustardsauce** [comment]
I'm really glad to hear that and I'm looking forward to it. Thank you.

**Comment by OmarHamdoun** [comment]
it works on windows 8 with vs2013  without OGUIFileBrowser 
add 
#ifdef _WIN32
#include <io.h>
#else
#include <unistd.h>
#endif

**Comment by Mustardsauce** [comment]
How about Windows 10?
Have you ever tested it?

**Comment by OmarHamdoun** [comment]
hi you can test the modification  
please download the zip file
https://drive.google.com/open?id=0B6p4SMGaNrh2cnNUS3NVOFJKaVU
download glew-2.0.0
https://sourceforge.net/projects/glew/files/glew/2.0.0/glew-2.0.0.zip/download
I used opencv 3.2 &visual studio 2013 
if you need any help please tell me

**Comment by Mustardsauce** [comment]
Thank you for your helps. I'll try it.

**Comment by damiles** [comment]
I create new [branch ](https://github.com/damiles/OpenCVGUI/tree/feautre/windows_porting) to port it correctly, now works with basic file browser support

And there are now a precompiled version: [Beta Version](https://github.com/damiles/OpenCVGUI/releases/download/0.1/OpenCVGUI_Windows_precompiled.zip).
