### ISSUE TITLE
How to install to Visual Studio project in Windows?

### ISSUE THREAD

**Issue by WinstonVM** [damiles/OpenCVGUI#8]
How do I install this to my project in Visual Studio in Windows? I have the OpenCV library installed as well

**Comment by damiles** [comment]
There is a prebuilt library in https://github.com/damiles/OpenCVGUI/releases/download/0.1/OpenCVGUI_Windows_precompiled.zip that you can download and import in your project

**Comment by WinstonVM** [comment]
Got it! Thanks
